database:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: daniel
    POSTGRES_PASSWORD: daniel
    POSTGRES_DB: demo

eureka:
  image: netflixoss/eureka:1.3.1
  ports:
    - "8080:8080"

kafka:
  image: spotify/kafka
  restart: allways
  ports:
    - "2181:2181"
    - "9092:9092"
  environment:
    ADVERTISED_HOST: "192.168.99.100"
    ADVERTISED_PORT: "9092"