database:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: daniel
    POSTGRES_PASSWORD: daniel
    POSTGRES_DB: demo

eureka:
  image: netflixoss/eureka:1.1.142
  ports:
    - "8080:8080"
    