database:
  image: postgres
  ports:
    - "13142:5432"
  environment:
    POSTGRES_USER: daniel
    POSTGRES_PASSWORD: daniel
    POSTGRES_DB: demo

eureka:
  image: netflixoss/eureka:1.3.1
  ports:
    - "8080:8080"

kafka:
  image: spotify/kafka
  restart: allways
  ports:
    - "2181:2181"
    - "9092:9092"
  environment:
    ADVERTISED_HOST: "192.168.99.100"
    ADVERTISED_PORT: "9092"

app:
 image: java:8
 working_dir: /app
 volumes:
   - ./build/libs:/app
 command: java -jar -Dspring.profiles.active=dev /app/demo-0.0.1-SNAPSHOT.jar
 ports:
   - "8082:8000"
 links:
   - database:database
   - kafka:kafka
   - eureka:eureka
 log_opt:
   max-size: "100k"
   max-file: "20"